# Generated by Django 4.2.2 on 2024-05-06 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=400)),
                ('unidade_medida', models.CharField(choices=[('UNID', 'Unidade'), ('CX', 'Caixa'), ('REACAO', 'Reação'), ('ALIQ', 'Alíquota'), ('KIT', 'Kit'), ('PLACA', 'Placa'), ('PCT', 'Pacote'), ('RACK', 'Rack'), ('TUBO', 'Tubo'), ('uL', 'Microlitro'), ('FR', 'Fração')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-value']},
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='setor', to='score.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('ENT', 'Entrada'), ('SAI', 'Saída')], max_length=6)),
                ('quantidade', models.CharField(choices=[('ENT', 'Entrada'), ('SAI', 'Saída')], max_length=3)),
                ('data_controle', models.DateTimeField(auto_now_add=True)),
                ('data_vencimento', models.DateTimeField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='funcionario', to='score.funcionario')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='produto', to='score.produto')),
            ],
        ),
    ]
