# Generated by Django 4.2.2 on 2024-05-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_alter_estoque_quantidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'ordering': ['produto', 'acao', 'data_controle', 'data_vencimento', 'funcionario']},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome', 'setor']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['marca', 'descricao', 'unidade_medida']},
        ),
        migrations.AlterField(
            model_name='estoque',
            name='data_vencimento',
            field=models.DateField(),
        ),
    ]
