# Generated by Django 5.0.4 on 2024-05-14 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_produto_referencia_alter_estoque_data_vencimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'ordering': ['produto', 'acao', 'data_controle', 'funcionario']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['referencia', 'marca', 'descricao', 'unidade_medida']},
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='data_vencimento',
        ),
    ]
