# Generated by Django 5.0.4 on 2024-05-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_alter_estoque_options_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='data_controle',
            field=models.DateTimeField(),
        ),
    ]
