# Generated by Django 4.2.2 on 2024-11-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0007_alter_estoque_data_controle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['codigo_barras', 'referencia', 'marca', 'descricao', 'unidade_medida']},
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
